### ISSUE TITLE
GeoServer 2.22.3 and GS 2.21.5 release

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/geoserver#348]
```[tasklist]
### Tasks
- [x] Configure ALL builds to use JDK8
- [x] Jenkins GeoTools-Release GT 28.3
- [x] Jenkins GeoTools-Release-Publish GT 28.3
- [x] Jenkins GeoTools-Release GT 27.5
- [x] Jenkins GeoTools-Release-Publish GT 27.5
- [x] JIRA Release 28.3 (Check commits)
- [x] JIRA Create release 28.4
- [x] JIRA Release 27.5 (Check commits)
- [x] JIRA Create release 27.6
- [x] GT Blogpost 28.3
- [x] GT Blogpost 27.5 (PREVIEW: https://www.blogger.com/u/1/blog/post/edit/116830172286767929/6265381503239771102)
- [x] GWC 1.22.2
- [x] GWC 1.21.5
- [x] Configure GeoTools builds to use JDK11
- [x] Jenkins GeoServer-Release GS 2.22.3
- [x] Send Email to DEVEL for testing and WAIT
- [x] --------------> WAIT <------------
- [x] AFTER CONFIRM: Jenkins GeoServer-Release Publish GS 2.22.3
- [x] Jenkins GeoServer-Release GS 2.21.5
- [x] Send Email to DEVEL for testing and WAIT
- [x] WAIT
- [x] AFTER CONFIRM: Jenkins GeoServer-Release Publish GS 2.21.5
- [x] Configure GeoServer builds to use JDK11
- [x] JIRA GS Release 2.22.3 (Check commits)
- [x] JIRA Create release 2.22.4
- [x] GS Blogpost 2.22.3 (PR:https://github.com/geoserver/geoserver.github.io/pull/146)
- [x] Release the GS 2.22.3 TAG
- [x] JIRA Release 2.21.5 (Check commits)
- [x] Release the GS 2.21.5 TAG
- [x] GS Blogpost 2.21.5 (PR:https://github.com/geoserver/geoserver.github.io/pull/148)
```
Towards the end of April
